version: '3'
services:
  nestjs:
    build: .
    volumes:
      - .:/home/nestjs/
      - /home/nestjs/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://nestjs@postgres/nestjs
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_DB: nestjs